name: "BedrockConnect Add-on"
version: "1.51"
slug: "bedrockconnect"
description: "A Home Assistant add-on for BedrockConnect"
arch:
  - aarch64
  - amd64
startup: "services"
boot: "auto"
options:
  servers: []
schema:
  servers:
    - name: str
      address: str
      port: int
map:
  - config:rw
ports:
  "19132/udp": 19132
init: true
environment:
  BC_CUSTOM_SERVERS: "/data/bedrock_servers.json"
image: "pugmatt/bedrock-connect"